[package]
name = "adventofcode-2024-day-template"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13"
rustc-hash = "2.1"
regex = "1.11"
strum = { version = "0.26", features = ["derive"] }

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
