[package]
name = "adventofcode-2024-day-05"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13"
regex = "1.11"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
